DATA: # arguments that will be passed to get_dataloaders
  batch_size: 32
  points_per_circle: 5
  n_radius: 2

MODEL:
  model_name: ConditionalMLP_CDCD
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 2
    output_dim: 10
    n_hidden: 4
    latent_dim: 32

TRAINING: # arguments that will be passed to the trainer
  criterion_str: CrossEntropyLoss
  optimizer:
    optimizer_name: AdamW
    PARAMS:
      lr: 0.001
  epochs: 100
  logdir: "./logs/CDCD/"
  use_logger: True
  timesteps: 50
  prediction_type: "sample"
  beta_schedule: "cumulative"
  lambda_snr_integral: 0.001
  learn_snr: False
  clip_sample: False

# SWEEP: # arguments to sweep over and their values
#   p_detach_snr_loss:
#     min: 0.25
#     max: 1.
#     n: 4