DATA: # arguments that will be passed to get_dataloaders
  name: "classifier"
  batch_size: 128
  binary: True
  noise_std: 1.0e-3
  exclude: "pos_vj"
  data_path: "/home/atari_ws/data/learning_jump_feasibility"

MODEL:
  model_name: MLP
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 46
    output_dim: 1
    n_hidden: 4
    latent_dim: 32

TRAINING: # arguments that will be passed to the trainer
  criterion_str: BCEWithLogitsLoss
    PARAMS:
      
  optimizer:
    optimizer_name: Adam
    PARAMS:
      lr: 0.001
  epochs: 75
  logdir: "./logs/MLPclassifierBinary/"
  use_logger: True
  ckpt_every: -1
  # lr_scheduler:
  #   lr_scheduler_name: ExponentialLR
  #   PARAMS:
  #     gamma: 0.96

SWEEP: # arguments to sweep over and their values
  # latent_dim: [16, 32, 64]
  # n_hidden: [3, 4]
  # batch_size: [32, 64, 128]
  # lr:
  #   min: 0.0001
  #   max: 0.001
  #   n: 2
  #   logspace: True